// <auto-generated />
using System;
using Convy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Convy.Infrastructure.Migrations
{
    [DbContext(typeof(ConvyDbContext))]
    [Migration("20260530102509_AddReferentialIntegrityConstraints")]
    partial class AddReferentialIntegrityConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Convy.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("metadata");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.HasKey("Id");

                    b.HasIndex("PerformedBy")
                        .HasDatabaseName("ix_activity_logs_performed_by");

                    b.HasIndex("HouseholdId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_activity_logs_household_id_created_at");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.AiUsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AudioDurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("audio_duration_seconds");

                    b.Property<int?>("AudioTokens")
                        .HasColumnType("integer")
                        .HasColumnName("audio_tokens");

                    b.Property<int?>("CachedTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cached_tokens");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_type");

                    b.Property<long?>("EstimatedCostMicros")
                        .HasColumnType("bigint")
                        .HasColumnName("estimated_cost_micros");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("feature");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operation");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<int?>("ReasoningTokens")
                        .HasColumnType("integer")
                        .HasColumnName("reasoning_tokens");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TextTokens")
                        .HasColumnType("integer")
                        .HasColumnName("text_tokens");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ai_usage_events_created_at");

                    b.HasIndex("HouseholdId", "CreatedAt")
                        .HasDatabaseName("ix_ai_usage_events_household_id_created_at");

                    b.HasIndex("Feature", "Operation", "CreatedAt")
                        .HasDatabaseName("ix_ai_usage_events_feature_operation_created_at");

                    b.ToTable("ai_usage_events", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.BackupRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("backup_type");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("verification_status");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_backup_runs_started_at");

                    b.HasIndex("Status", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_backup_runs_status_started_at");

                    b.ToTable("backup_runs", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("en")
                        .HasColumnName("locale");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_device_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_tokens_user_id");

                    b.ToTable("device_tokens", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_households_created_by");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.HouseholdList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_household_lists_created_by");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_household_lists_household_id");

                    b.HasIndex("HouseholdId", "IsArchived")
                        .HasDatabaseName("ix_household_lists_household_id_is_archived");

                    b.ToTable("household_lists", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.HouseholdMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("HouseholdId", "UserId")
                        .IsUnique();

                    b.ToTable("household_memberships", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_invites_created_by");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_invites_household_id");

                    b.HasIndex("UsedBy")
                        .HasDatabaseName("ix_invites_used_by");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_date");

                    b.Property<string>("NormalizedTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("RecurrenceFrequency")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence_frequency");

                    b.Property<int?>("RecurrenceInterval")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence_interval");

                    b.Property<DateTime?>("ReturnedToPendingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_to_pending_at");

                    b.Property<Guid?>("ReturnedToPendingBy")
                        .HasColumnType("uuid")
                        .HasColumnName("returned_to_pending_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("CompletedBy")
                        .HasDatabaseName("ix_list_items_completed_by");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_list_items_created_by");

                    b.HasIndex("ListId")
                        .HasDatabaseName("ix_list_items_list_id");

                    b.HasIndex("NextDueDate")
                        .HasDatabaseName("ix_list_items_next_due_date")
                        .HasFilter("\"next_due_date\" IS NOT NULL");

                    b.HasIndex("ReturnedToPendingBy")
                        .HasDatabaseName("ix_list_items_returned_to_pending_by");

                    b.HasIndex("ListId", "IsCompleted")
                        .HasDatabaseName("ix_list_items_list_id_is_completed");

                    b.HasIndex("Source", "CreatedAt")
                        .HasDatabaseName("ix_list_items_source_created_at");

                    b.HasIndex("ListId", "IsCompleted", "CompletedAt")
                        .HasDatabaseName("ix_list_items_list_id_is_completed_completed_at");

                    b.HasIndex("ListId", "IsCompleted", "CreatedAt")
                        .HasDatabaseName("ix_list_items_list_id_is_completed_created_at");

                    b.HasIndex("ListId", "IsCompleted", "ReturnedToPendingAt")
                        .HasDatabaseName("ix_list_items_list_id_is_completed_returned_at");

                    b.HasIndex("ListId", "NormalizedTitle", "IsCompleted")
                        .HasDatabaseName("ix_list_items_list_id_normalized_title_is_completed");

                    b.ToTable("list_items", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.McpIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_name");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_mcp_idempotency_records_expires_at");

                    b.HasIndex("UserId", "ClientId", "KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_idempotency_records_user_client_key");

                    b.ToTable("mcp_idempotency_records", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.McpOAuthAuthorizationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_id");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("code_challenge");

                    b.Property<string>("CodeChallengeMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_challenge_method");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("redirect_uri");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resource");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("scopes");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_oauth_authorization_codes_code_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_mcp_oauth_authorization_codes_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mcp_oauth_authorization_codes_user_id");

                    b.ToTable("mcp_oauth_authorization_codes", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.McpOAuthConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resource");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("scopes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("ix_mcp_oauth_consents_revoked_at");

                    b.HasIndex("UserId", "ClientId", "Resource")
                        .HasDatabaseName("ix_mcp_oauth_consents_user_id_client_id_resource");

                    b.ToTable("mcp_oauth_consents", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.McpOAuthRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resource");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("scopes");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_mcp_oauth_refresh_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_mcp_oauth_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mcp_oauth_refresh_tokens_user_id");

                    b.ToTable("mcp_oauth_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.McpToolInvocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_type");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_mcp_tool_invocations_client_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_mcp_tool_invocations_created_at");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_mcp_tool_invocations_household_id");

                    b.HasIndex("ToolName")
                        .HasDatabaseName("ix_mcp_tool_invocations_tool_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mcp_tool_invocations_user_id");

                    b.ToTable("mcp_tool_invocations", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.NotificationPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ItemTaskChanges")
                        .HasColumnType("boolean")
                        .HasColumnName("item_task_changes");

                    b.Property<bool>("ItemsAdded")
                        .HasColumnType("boolean")
                        .HasColumnName("items_added");

                    b.Property<bool>("ItemsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("items_completed");

                    b.Property<bool>("ListChanges")
                        .HasColumnType("boolean")
                        .HasColumnName("list_changes");

                    b.Property<bool>("MemberChanges")
                        .HasColumnType("boolean")
                        .HasColumnName("member_changes");

                    b.Property<bool>("TaskReminders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("task_reminders");

                    b.Property<bool>("TasksAdded")
                        .HasColumnType("boolean")
                        .HasColumnName("tasks_added");

                    b.Property<bool>("TasksCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("tasks_completed");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_preferences_user_id");

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.SystemMetricSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<long?>("DiskFreeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("disk_free_bytes");

                    b.Property<long?>("DiskTotalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("disk_total_bytes");

                    b.Property<double?>("LoadAverage1m")
                        .HasColumnType("double precision")
                        .HasColumnName("load_average_1m");

                    b.Property<long?>("MemoryAvailableBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_available_bytes");

                    b.Property<long?>("MemoryTotalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_total_bytes");

                    b.Property<long?>("PostgresDataSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("postgres_data_size_bytes");

                    b.Property<long?>("UptimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("uptime_seconds");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("ix_system_metric_snapshots_captured_at");

                    b.ToTable("system_metric_snapshots", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<string>("NormalizedTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ReminderAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_at_utc");

                    b.Property<DateTime?>("ReminderSentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_sent_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_task_items_assigned_to_user_id");

                    b.HasIndex("CompletedBy")
                        .HasDatabaseName("ix_task_items_completed_by");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_task_items_created_by");

                    b.HasIndex("ListId")
                        .HasDatabaseName("ix_task_items_list_id");

                    b.HasIndex("ListId", "AssignedToUserId")
                        .HasDatabaseName("ix_task_items_list_id_assigned_to_user_id");

                    b.HasIndex("ListId", "CreatedAt")
                        .HasDatabaseName("ix_task_items_list_id_created_at");

                    b.HasIndex("ListId", "DueDate")
                        .HasDatabaseName("ix_task_items_list_id_due_date");

                    b.HasIndex("ListId", "IsCompleted")
                        .HasDatabaseName("ix_task_items_list_id_is_completed");

                    b.HasIndex("ReminderAtUtc", "ReminderSentAtUtc")
                        .HasDatabaseName("ix_task_items_reminder_at_utc_reminder_sent_at_utc");

                    b.HasIndex("ListId", "IsCompleted", "CreatedAt")
                        .HasDatabaseName("ix_task_items_list_id_is_completed_created_at");

                    b.HasIndex("ListId", "NormalizedTitle", "IsCompleted")
                        .HasDatabaseName("ix_task_items_list_id_normalized_title_is_completed");

                    b.ToTable("task_items", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firebase_uid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.VoiceParseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AudioDurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("audio_duration_seconds");

                    b.Property<long?>("AudioSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("audio_size_bytes");

                    b.Property<int?>("CachedTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cached_tokens");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("EstimatedCostMicros")
                        .HasColumnType("bigint")
                        .HasColumnName("estimated_cost_micros");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<int>("ParsedItemsCount")
                        .HasColumnType("integer")
                        .HasColumnName("parsed_items_count");

                    b.Property<int?>("ReasoningTokens")
                        .HasColumnType("integer")
                        .HasColumnName("reasoning_tokens");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_voice_parse_events_created_at");

                    b.HasIndex("HouseholdId", "CreatedAt")
                        .HasDatabaseName("ix_voice_parse_events_household_id_created_at");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_voice_parse_events_status_created_at");

                    b.ToTable("voice_parse_events", (string)null);
                });

            modelBuilder.Entity("Convy.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("Convy.Domain.Entities.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_logs_households_household_id");

                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_logs_users_performed_by");
                });

            modelBuilder.Entity("Convy.Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_tokens_users_user_id");
                });

            modelBuilder.Entity("Convy.Domain.Entities.Household", b =>
                {
                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_households_users_created_by");
                });

            modelBuilder.Entity("Convy.Domain.Entities.HouseholdList", b =>
                {
                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_household_lists_users_created_by");

                    b.HasOne("Convy.Domain.Entities.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_household_lists_households_household_id");
                });

            modelBuilder.Entity("Convy.Domain.Entities.HouseholdMembership", b =>
                {
                    b.HasOne("Convy.Domain.Entities.Household", null)
                        .WithMany("Memberships")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Convy.Domain.Entities.Invite", b =>
                {
                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invites_users_created_by");

                    b.HasOne("Convy.Domain.Entities.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invites_households_household_id");

                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invites_users_used_by");
                });

            modelBuilder.Entity("Convy.Domain.Entities.ListItem", b =>
                {
                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CompletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_list_items_users_completed_by");

                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_list_items_users_created_by");

                    b.HasOne("Convy.Domain.Entities.HouseholdList", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_items_household_lists_list_id");

                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReturnedToPendingBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_list_items_users_returned_to_pending_by");
                });

            modelBuilder.Entity("Convy.Domain.Entities.NotificationPreferences", b =>
                {
                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_preferences_users_user_id");
                });

            modelBuilder.Entity("Convy.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_task_items_users_assigned_to_user_id");

                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CompletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_task_items_users_completed_by");

                    b.HasOne("Convy.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_items_users_created_by");

                    b.HasOne("Convy.Domain.Entities.HouseholdList", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_items_household_lists_list_id");
                });

            modelBuilder.Entity("Convy.Domain.Entities.Household", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Convy.Domain.Entities.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
